version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etc/nginx/cache
      - ./certs/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  app_1:
    build: ./app/.
    container_name: app_1
    environment: 
      - APP_NAME='app_1'
    expose:
      - "80"
  app_2:
    build: ./app/.
    container_name: app_2
    environment: 
      - APP_NAME='app_2'
    expose:
      - "80"
  app_3:
    build: ./app/.
    container_name: app_3
    environment: 
      - APP_NAME='app_3'
    expose:
      - "80"
